### PR TITLE
Find the subject buffer for parsing.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
This allows the editor to work fine in Diff Viewer.

### CODE REVIEW

**Comment by mhutch** [comment]
Would it be more appropriate to put this in MSBuildParserProvider.GetParser?

**Comment by KirillOsenkov** [comment]
Yes, how's this?

**Comment by mhutch** [comment]
Better! You could still end up with two parsers if one thing uses GetParser on the projection and another thing uses it on the subject buffer though. Wonder whether we could make it safer.

**Comment by KirillOsenkov** [comment]
OK, valid point. How about this?

**Pull request merged**
