### PR TITLE
Parsing and analyzer fixes

### PR DESCRIPTION
**Pull request by mhutch**
Fixes for #121, #123 and a few other parsing and analyzer issues

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
I'm trying this change out and seeing an ArgumentException when adding MSBuildSessionContext to the session.Properties (the session already has a context in the property bag):

image

Somehow InitializeMSBuildSessionContext is running twice for the same session?

Repro: type out `<P>` under the debugger.

**Comment by KirillOsenkov** [comment]
The good news is that other issues seem to be fixed! I'm able to type out a simple project from scratch without hitting more exceptions.

**Comment by KirillOsenkov** [comment]
I haven't seen the double-add of InitializeMSBuildSessionContext in the main branch, but perhaps because it was obscured by the other two exceptions that you've fixed in this PR?

**Comment by mhutch** [comment]
Interesting, I'm not seeing that when debugging in VS 17.8. That code does assume that the session will never have GetCompletionItems called multiple times, which may not be correct, but I'm not sure how to recreate that situation you're seeing.

**Comment by KirillOsenkov** [comment]
Oh, this PR is not up-to-date, this PR is on d057134, but the latest in the parsing-fixes branch is bbfdefd.

Let me try latest.

**Comment by KirillOsenkov** [comment]
Nice, the latest https://github.com/mhutch/MonoDevelop.MSBuildEditor/commit/bbfdefd786604a369591f87df4800052f14656cc works just fine, not able to see any exceptions.

**Review by KirillOsenkov — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
Hmm, but I'm not sure how can it be that this PR doesn't show the latest commit from the branch??

**Pull request merged**
