### PR TITLE
Update to latest MonoDevelop.Xml

### PR DESCRIPTION
**Pull request by KirillOsenkov**

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
@mhutch if you're interested

**Comment by KirillOsenkov** [comment]
Should we remove the Mac leg or disable it?

**Comment by KirillOsenkov** [comment]
FYI @SandyArmstrong:

/Users/runner/work/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuildEditor/.nuget/packages/microsoft.visualstudiomac.sdk/17.0.0/build/Microsoft.VisualStudioMac.Sdk.targets(132,5): error : Could not resolve addin reference 'MonoDevelop.SourceEditor2' [/Users/runner/work/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuildEditor/MonoDevelop.MSBuildEditor.csproj]

Not sure if we need to build this repo for Mac @mhutch?

**Comment by mhutch** [comment]
Updated MonoDevelop.Xml in https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/76

I previously disabled the Mac leg in https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/71/commits/0b2796088016e7625113c69dbec94bb290274a4b as I haven't ported the extension to VSMac 17.x yet

**Comment by KirillOsenkov** [comment]
Thanks!

**Comment by mhutch** [comment]
FWIW am happy to take PRs to fix the Mac build :)

The official Mac extensibility targets didn't work for me as they couldn't resolve any of the packages; I think I was missing some feed? I was considering fixing it by porting the MonoDevelop.Addins build logic package as well.

**Pull request closed without merging**
